### ISSUE TITLE
Constexpr string hashing

### ISSUE THREAD

**Issue by Zanthelo** [hpicgs/yats#24]
We need a function which hashes a std::string / c string at compile time and returns a size_t. Additionally we should provide a user_literal with the same functionality.

**Comment by Highlife1911** [comment]
Instead of generating a real hash you can generate an arithmetic representation of the string. To use this you need to convert the string to a uint64_t. When using an alphabet of 32 characters it is possible to store up to 12 characters inside a single size_t. The store should ignore the case and should allow in addition to the 26 alphabetic characters also "\0_*/ -". Characters that are not in the pool should be replaced with
