### ISSUE TITLE
OSX build times on Travis are very high

### ISSUE THREAD

**Issue by lawben** [hpicgs/yats#37]
We should discuss how we want to deal with the long waiting times for OSX builds on Travis.

Options:
  - leave it as is and wait for jobs to be scheduled
  - limit OSX to build only release or debug
  - remove OSX from CI (probably worst of the ideas)

**Comment by Highlife1911** [comment]
Due to limited resources from Travis a build can take up to 12h. Removing debug or release does not help because we have a long initial waiting time that will stay the same. We have to keep OSX builds because in the past we had cases where everything was fine, but the OSX build failed. It might be a good idea to allow merging even if the ci is not finished (at least when the chance is very low that it won't build).
